server.port=3456

# Providers (智谱 Coding Plan)
ccr.providers[0].name=zhipu
#ccr.providers[0].url=https://open.bigmodel.cn/api/anthropic/v1/messages
ccr.providers[0].url=https://open.bigmodel.cn/api/paas/v4/chat/completions
ccr.providers[0].apiKey=09e477495f8646c9924b30ad78878f2c.0uL1wJurQv3ZJQnv
ccr.providers[0].transformer.use[0]=openrouter
#ccr.providers[0].transformer.use[0]=Anthropic

# Router Configuration
ccr.router.default=zhipu,glm-5.1
ccr.router.think=zhipu,glm-5.1
ccr.router.background=zhipu,glm-5.1
ccr.router.longContext=zhipu,glm-5.1
ccr.router.webSearch=zhipu,glm-5.1
ccr.router.longContextThreshold=1000
